apiVersion: v1
kind: Service
metadata:
  labels:
    run: logistics-app
    razee/watch-resource: "true"
  name: logistics-svc
  namespace: logistics
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: web
    targetPort: 8080
  selector:
    run: logistics-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: logistics-app
    razee/watch-resource: "true"
  name: logistics-app
  namespace: logistics
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      run: logistics-app
  template:
    metadata:
      labels:
        run: logistics-app
    spec:
      containers:
      - image: jsloyer/hello-app:latest
        name: logistics-app
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        env:
          - name: message
            value: "Hello Everyone"
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"